Update readme-gen.yml

diff --git a/.github/workflows/readme-gen.yml b/.github/workflows/readme-gen.yml
--- a/.github/workflows/readme-gen.yml
+++ b/.github/workflows/readme-gen.yml
@@ -10,7 +10,7 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Run README generator
-        run: python readme_generate.py &> log.txt || echo -e "**Error generating the README.**<br>Logs have been provided below for debugging purposes.\n\n\`\`\`\n$(cat log.txt)\n\`\`\`" >> $GITHUB_STEP_SUMMARY && exit 1
+        run: python readme_generate.py || echo "**Error generating the README.**<br>Please check the workflow logs for more information." > $GITHUB_STEP_SUMMARY && exit 1
       - name: Push
         run: |
           rm log.txt
@@ -19,5 +19,5 @@ jobs:
           git add .
           git commit -m "Generate README"
           git push
-      - name: Show new README as job summary
+      - name: Show new README on workflow page
         run: echo -e "**The new README has been generated!**<br>The README that was generated by this run can be found below.\n\n$(cat readme.md)" > $GITHUB_STEP_SUMMARY
