Update readme-gen.yml

diff --git a/.github/workflows/readme-gen.yml b/.github/workflows/readme-gen.yml
--- a/.github/workflows/readme-gen.yml
+++ b/.github/workflows/readme-gen.yml
@@ -10,13 +10,13 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Run README generator
-        run: python readme_generate.py
-      - name: Show new README as job summary
-        run: echo -e "**The new README has been generated!**<br>The README that was generated by this run can be found below.\n\n$(cat readme.md)" >> $GITHUB_STEP_SUMMARY
+        run: python readme_generate.py || echo "**Error generating the README.**" >> $GITHUB_STEP_SUMMARY
       - name: Push
         run: |
           git config --global user.email "actions-user@users.noreply.github.com"
           git config --global user.name "actions-user"
           git add .
           git commit -m "Generate README"
-          git push || exit 0
+          git push || echo "**Error sending README to the repository.**<br>The most common cause is that no changes were made to one of the licenses." >> $GITHUB_STEP_SUMMARY
+      - name: Show new README as job summary
+        run: echo -e "**The new README has been generated!**<br>The README that was generated by this run can be found below.\n\n$(cat readme.md)" >> $GITHUB_STEP_SUMMARY
